
INSERT INTO EQUIPOS VALUES (1,'Argentina',2,1);
INSERT INTO EQUIPOS VALUES (2,'Paises Bajos',0,2);
INSERT INTO EQUIPOS VALUES (3,'Croacia',0,3);
INSERT INTO EQUIPOS VALUES (4,'Brasil',5,4);
INSERT INTO EQUIPOS VALUES (5,'Inglaterra',1,5);
INSERT INTO EQUIPOS VALUES (6,'Francia',2,6);
INSERT INTO EQUIPOS VALUES (7,'Marruecos',0,7);
INSERT INTO EQUIPOS VALUES (8,'Portugal',0,8);
